version: "2"

linters:
  enable:
    - govet       # Reports suspicious constructs (official go tool)
    - errcheck    # Checks that errors are handled
    - staticcheck # Broad static analysis (SA*, S1*, QF* checks)
    - ineffassign # Detects ineffectual assignments
    - unused      # Reports unused code (vars, funcs, types, consts)
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment # Not enforced yet — can be enabled later
    errcheck:
      check-type-assertions: true
      check-blank: true
    staticcheck:
      checks:
        - "all"
        - "-SA1019" # Allow deprecated API usage for now
  exclusions:
    # Don't report issues in generated code (sqlc output)
    paths:
      - internal/generated

formatters:
  enable:
    - gofmt # Ensures code is gofmt-formatted
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"

issues:
  # Fail on new issues only (do not fail on pre-existing ones in one shot)
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
