version: "2"

linters:
  enable:
    - govet       # Reports suspicious constructs (official go tool)
    - errcheck    # Checks that errors are handled
    - staticcheck # Broad static analysis (SA*, S1*, QF* checks)
    - gosimple    # Suggests simplifications
    - ineffassign # Detects ineffectual assignments
    - gofmt       # Ensures code is gofmt-formatted
    - unused      # Reports unused code (vars, funcs, types, consts)

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment # Not enforced yet — can be enabled later

  errcheck:
    check-type-assertions: true
    check-blank: true

  staticcheck:
    checks:
      - "all"
      - "-SA1019" # Allow deprecated API usage for now

  gofmt:
    simplify: true
    rewrite-rules:
      - pattern: "interface{}"
        replacement: "any"

issues:
  # Don't report issues in generated code (sqlc output)
  exclude-dirs:
    - internal/generated

  # Fail on new issues only (do not fail on pre-existing ones in one shot)
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
